// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
/// <reference types="node" />
import "dotenv/config";
import { defineConfig } from "prisma/config";

const DATABASE_URL =
  process.env.NODE_ENV === "test"
    ? process.env.DATABASE_URL_TESTING
    : process.env.NODE_ENV === "production"
      ? process.env.DATABASE_URL_PRODUCTION
      : process.env.DATABASE_URL;
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: DATABASE_URL,
  },
});
