export const userSafeSelect = {
  id: true,
  firstName: true,
  fatherName: true,
  grandFatherName: true,
  email: true,
  christianName: true,
  phoneNumber: true,
  role: true,
  permissions: true,
  gender: true,
  admissionYear: true,
  studentId: true,
  isAccountVerified: true,
  isEmailVerified: true,
  dormitoryBlock: true,
  dormitoryNumber: true,
  department: true,
  loginAttempts: true,
  lastLoginAt: true,
  createdAt: true,
  updatedAt: true,
};
